export default {
	SET_CURRENT_PACK: 'SET_CURRENT_PACK',
	CLOSE_CURRENT_PACK: 'CLOSE_CURRENT_PACK',
	OPEN_GAME_MODE: 'OPEN_GAME_MODE',
	CLOSE_GAME_MODE: 'CLOSE_GAME_MODE',
	SET_PACK_INFO: 'SET_PACK_INFO',
	OPEN_HELP: 'OPEN_HELP',
	CLOSE_HELP: 'CLOSE_HELP',
	TOGGLE_SOUND: 'TOGGLE_SOUND',
	SHOW_LOADING: 'SHOW_LOADING',
	HIDE_LOADING: 'HIDE_LOADING',
	TOGGLE_DASHBOARD: 'TOGGLE_DASHBOARD'
};
