export default {
	SET_CURRENT_PACK: 'SET_CURRENT_PACK',
	CLOSE_CURRENT_PACK: 'CLOSE_CURRENT_PACK',
	OPEN_GAME_MODE: 'OPEN_GAME_MODE',
	CLOSE_GAME_MODE: 'CLOSE_GAME_MODE',
	SET_PACK_INFO: 'SET_PACK_INFO'
};
